apiVersion: v1
kind: Secret
metadata:
  name: cluster-config
  namespace: crossplane-system
type: Opaque
stringData:
# This tell Crossplane use token to connect to the cluster
  kubeconfig: |
    apiVersion: v1
    kind: Config
    clusters:
    - cluster:
        server: https://kubernetes.default.svc
        insecure-skip-tls-verify: true
      name: local
    contexts:
    - context:
        cluster: local
      name: local
    current-context: local
    users:
    - name: local

---

apiVersion: kubernetes.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: InjectedIdentity
