apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xdatabaseenvironments.platform.example.com
spec:
  group: platform.example.com
  names:
    kind: XDatabaseEnvironment
    plural: xdatabaseenvironments
  claimNames:
    kind: DatabaseEnvironment
    plural: databaseenvironments  
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  teamName:
                    type: string
                  dbSize:
                    type: string
                    enum: ["small", "medium", "large"]
                required:
                  - teamName
                  - dbSize
                    
              